import { useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/card/card";
import { GET_LIST } from "../queries";
import styles from "../styles/Home.module.css";
import { IAsaList } from "../types";

const Home: NextPage = () => {
  const { loading, error, data } = useQuery<IAsaList>(GET_LIST);

  console.log(data?.asalist.result);

  if (loading) {
    return <h1>loading...</h1>;
  }

  if (error) {
    return <h1>Error de o...</h1>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.ma}>
        <div>
          <div className={styles.titleBar}>
            <div className={styles.title}>
              <Image
                src="/asset/headerlogo.svg"
                alt="head Logo"
                width={108.94}
                height={50}
              />
            </div>
            <div className={styles.button}>
              <button className={styles.butt}>ANALYZE ASAs</button>
            </div>
          </div>
        </div>
        <p className={styles.description}>
          List of Algorand Standard Assets on ASAlytics
        </p>

        <div className={styles.grid}>
          {data?.asalist.result.map((item) => (
            <Card
              key={item.assetId}
              assetId={item.assetId}
              name={item.name}
              logo={item.logo}
              available={false}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
